AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Creates the Lambda function and API for the PyTorch inference application.

Parameters: 
  BucketName: 
    Type: String
    Default: somebucket
    Description: Enter the name of the S3 bucket storing your PyTorch model artefacts.
  ObjectKey: 
    Type: String
    Default: somekey
    Description: Enter the S3 object key path of your PyTorch model artefacts.
  LambdaLayerArn:
    Type: String
    Default: "arn:aws:lambda:eu-west-1:934676248949:layer:pytorchv1-py36:1"
    Description: Enter the PyTorch Lambda Layer ARN. Defaults to a public one.

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst

Globals:
    Function:
        Timeout: 30

Resources:

  PyTorchFunction:
      Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
      Properties:
          CodeUri: pytorch/
          Handler: app.lambda_handler
          Runtime: python3.6
          MemorySize: 1024
          Environment:
            Variables:
              MODEL_BUCKET: !Ref BucketName
              MODEL_KEY: !Ref ObjectKey
          Policies:
            - S3ReadPolicy:
                BucketName: !Ref BucketName
          Layers:
            - !Ref LambdaLayerArn 
          Events:
              PyTorch:
                  Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
                  Properties:
                      Path: /invocations
                      Method: post
                        
Outputs:

    # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
    # Find out more about other implicit resources you can reference within SAM
    # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
    PyTorchApi:
      Description: "API Gateway endpoint URL for Prod stage for PyTorch function"
      Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/invocations/"

    PyTorchFunction:
      Description: "PyTorch Lambda Function ARN"
      Value: !GetAtt PyTorchFunction.Arn

    PyTorchFunctionIamRole:
      Description: "Implicit IAM Role created for PyTorch function"
      Value: !GetAtt PyTorchFunctionRole.Arn                        